base: Fix GCC 7.1.1 build error [#2535]
Fix the following build error when using GCC 7.1.1:

In file included from /home/opensaf/osaf_test_workdir/srcdir/opensaf-5.17.10/src/base/tests/osaf_timespec_average_test.cc:19:0:
/home/opensaf/osaf_test_workdir/googletest/googletest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long int; T2 = long unsigned int]’:
/home/opensaf/osaf_test_workdir/googletest/googletest/include/gtest/gtest.h:1421:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long int; T2 = long unsigned int; bool lhs_is_null_literal = false]’
/home/opensaf/osaf_test_workdir/srcdir/opensaf-5.17.10/src/base/tests/osaf_timespec_average_test.cc:38:3:   required from here
/home/opensaf/osaf_test_workdir/googletest/googletest/include/gtest/gtest.h:1392:11: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (lhs == rhs) {
       ~~~~^~~~~~
cc1plus: all warnings being treated as errors
  CXX      src/amf/amfd/tests/bin_testamfd-test_amfdb.o