pyosaf: fix saImmOmAdminOperationInvoke_2 [#1176]
exception when using saImmOmAdminOperationInvoke_2:
 ctypes.ArgumentError: argument 5: <type 'exceptions.TypeError'="">: expected LP_LP_SaImmAdminOperationParamsT instance instead of c_void_p_Array_1

Problem is the function marshalNullArray cannot handle an empty list.

Add type argument to marshalNullArray and use it to create array type properly.